<?php

/*Connection Information for the database
$def_coy - the default company that is pre-selected on login

'host' - the computer ip address or name where the database is. The default is 'localhost' assuming that the web server is also the sql server.

'port' - the computer port where the database is. The default is '3306'. Set empty for default.

'dbuser' - the user name under which the company database should be accessed.
  NB it is not secure to use root as the dbuser with no password - a user with appropriate privileges must be set up.

'dbpassword' - the password required for the dbuser to authorise the above database user.

'dbname' - the name of the database as defined in the RDMS being used. Typically RDMS allow many databases to be maintained under the same server.
'collation' - the character set used for the database.
'tbpref' - prefix on table names, or '' if not used. Always use non-empty prefixes if multiply company use the same database.
*/


if ($_SERVER["SERVER_NAME"]=='localhost'){
  $dbuser='faisal';
  $dbpass='123456';
}

$def_coy = 0;

$tb_pref_counter = 183;

$db_connections = array (
  0 =>
  array (
    'name' => 'Boxygen',
    'host' => 'localhost',
    'port' => '',
    'dbname' => 'pakerp_boxygen',
    'collation' => 'utf8_xx',
    'tbpref' => '0_',
    'dbuser' => $dbuser ?? 'pakerp_coy0',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'parent' => '',
    'app_id' => '1028052',
    'mapp' => '0',
    'dbparent' => '',
  ),
  1 =>
  array (
    'name' => 'AQUAP',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy1',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_aquap',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044036',
    'dbparent' => '',
  ),
  2 =>
  array (
    'name' => 'PAYROLL',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy2',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_payroll',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044128',
    'dbparent' => '',
  ),
  3 =>
  array (
    'name' => 'MASJID',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy3',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_masjid',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => 'AQUAP',
    'app_id' => '1044043',
    'dbparent' => '',
  ),
  4 =>
  array (
    'name' => 'DEMO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy4',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_demo',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044047',
    'dbparent' => '',
  ),
  5 =>
  array (
    'name' => 'ZQAGENCY',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy5',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_zqagency',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1043950',
    'dbparent' => '',
  ),
  6 =>
  array (
    'name' => 'MAAZTEST',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy6',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_maaztest',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044129',
    'dbparent' => '',
  ),
  7 =>
  array (
    'name' => '7SIGN',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy7',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_7sign',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => '',
    'app_id' => '1043713',
    'mapp' => '0',
    'dbparent' => '',
  ),
  8 =>
  array (
    'name' => 'SUMAIRENT',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy8',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_sumairent',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044032',
    'dbparent' => '',
  ),
  9 =>
  array (
    'name' => 'COMMSERVER',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy9',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_commserver',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044138',
    'dbparent' => '',
  ),
  10 =>
  array (
    'name' => 'FARASH',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy10',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_farash',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044109',
    'dbparent' => '',
  ),
  11 =>
  array (
    'name' => 'CITYTOOLS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy11',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_citytools',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044035',
    'dbparent' => '',
  ),
  12 =>
  array (
    'name' => 'CLEARING',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy12',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_clearing',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044110',
    'dbparent' => '',
  ),
  13 =>
  array (
    'name' => 'WATER',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy13',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_water',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063090',
    'dbparent' => '',
  ),
  14 =>
  array (
    'name' => 'ASIA',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy11',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_citytools',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => 'CITYTOOLS',
    'app_id' => '1044035',
    'dbparent' => 'CITYTOOLS',
  ),
  15 =>
  array (
    'name' => 'AYF-COMPANY',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy11',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_citytools',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => 'CITYTOOLS',
    'app_id' => '1044035',
    'dbparent' => 'CITYTOOLS',
  ),
  16 =>
  array (
    'name' => 'BASIT-ALI',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy11',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_citytools',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => 'CITYTOOLS',
    'app_id' => '1044035',
    'dbparent' => 'CITYTOOLS',
  ),
  17 =>
  array (
    'name' => 'ALIMUKHTAR',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy17',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_alimukhtar',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1331536',
    'dbparent' => '',
  ),
  18 =>
  array (
    'name' => 'ERDC',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy18',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_erdc',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044111',
    'dbparent' => '',
  ),
  19 =>
  array (
    'name' => 'POS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy19',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_pos',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1045130',
    'dbparent' => '',
  ),
  20 =>
  array (
    'name' => 'FAISAL',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy20',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_faisal',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  21 =>
  array (
    'name' => 'ZIQI',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy21',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_ziqi',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044112',
    'dbparent' => '',
  ),
  22 =>
  array (
    'name' => 'ECL',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy22',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_ecl',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063108',
    'dbparent' => '',
  ),
  23 =>
  array (
    'name' => 'FAYME',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy23',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_fayme',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063110',
    'dbparent' => '',
  ),
  24 =>
  array (
    'name' => 'CSF',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy24',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_csf',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063119',
    'dbparent' => '',
  ),
  25 =>
  array (
    'name' => 'OKASHA',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy25',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_okasha',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063122',
    'dbparent' => '',
  ),
  26 =>
  array (
    'name' => 'PAKBEE',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy26',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_pakbee',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => '',
    'mapp' => '0',
    'app_id' => '1063123',
    'dbparent' => '',
  ),
  27 =>
  array (
    'name' => 'BLINK',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy27',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_blink',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063124',
    'dbparent' => '',
  ),
  28 =>
  array (
    'name' => 'ZOHAIB',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy28',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_zohaib',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044099',
    'dbparent' => '',
  ),
  29 =>
  array (
    'name' => 'HSPAK',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy29',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_hspak',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063125',
    'dbparent' => '',
  ),
  30 =>
  array (
    'name' => 'COMM',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy30',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_comm',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  31 =>
  array (
    'name' => 'SAADTRADERS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy31',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_saadtraders',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063126',
    'dbparent' => '',
  ),
  32 =>
  array (
    'name' => 'ARFATTRADERS',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'SAADTRADERS',
    'dbuser' => $dbuser ?? 'pakerp_coy31',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_saadtraders',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063126',
    'dbparent' => 'SAADTRADERS',
  ),
  33 =>
  array (
    'name' => 'SICS',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'SAADTRADERS',
    'dbuser' => $dbuser ?? 'pakerp_coy31',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_saadtraders',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063126',
    'dbparent' => 'SAADTRADERS',
  ),
  34 =>
  array (
    'name' => 'COTPAK',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy34',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_cotpak',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044108',
    'dbparent' => '',
  ),
  35 =>
  array (
    'name' => 'BATCHEXP',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy35',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_batchexp',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1265479',
    'dbparent' => '',
  ),
  36 =>
  array (
    'name' => 'SWIFT',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy36',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_swift',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063131',
    'dbparent' => '',
  ),
  37 =>
  array (
    'name' => 'ADVMANU',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy37',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_advmanu',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1323163',
    'dbparent' => '',
  ),
  38 =>
  array (
    'name' => 'CELLPOR',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy38',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_cellpor',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  39 =>
  array (
    'name' => 'CELLROCK',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy39',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_cellrock',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  40 =>
  array (
    'name' => 'PCAPS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy40',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_pcaps',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => 'AQUAP',
    'app_id' => '1063142',
    'dbparent' => '',
  ),
  41 =>
  array (
    'name' => 'SCHOOL',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy41',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_school',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063140',
    'dbparent' => '',
  ),
  42 =>
  array (
    'name' => 'AFOHS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy42',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_afohs',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  43 =>
  array (
    'name' => 'MHA',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy31',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_saadtraders',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => 'SAADTRADERS',
    'app_id' => '1063126',
    'dbparent' => 'SAADTRADERS',
  ),
  44 =>
  array (
    'name' => 'LIVEDUCATE',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy44',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_liveducate',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  45 =>
  array (
    'name' => 'UNIVERSAL',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy45',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_universal',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063153',
    'dbparent' => '',
  ),
  46 =>
  array (
    'name' => 'EASYPRINT',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy46',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_easyprint',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => '7SIGN',
    'app_id' => '1043713',
    'mapp' => '0',
    'dbparent' => '',
  ),
  47 =>
  array (
    'name' => 'FRONTLINE',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy47',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_frontline',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063157',
    'dbparent' => '',
  ),
  48 =>
  array (
    'name' => 'MSHARIF',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy48',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_msharif',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  49 =>
  array (
    'name' => 'MAC',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy49',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_mac',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063160',
    'dbparent' => '',
  ),
  50 =>
  array (
    'name' => 'AMINMOQEEM',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy50',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_aminmoqeem',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063196',
    'dbparent' => '',
  ),
  51 =>
  array (
    'name' => 'REHMANBROTHERS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy51',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_rehmanbrothers',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063198',
    'dbparent' => '',
  ),
  52 =>
  array (
    'name' => 'BASIERANDCO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy52',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_basierandco',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  53 =>
  array (
    'name' => 'SHAMIQ',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy53',
    'dbpassword' => $dbpass ?? 'Pakistan1947',
    'dbname' => 'pakerp_shamiq',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  54 =>
  array (
    'name' => 'AASENTERPRISES',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy54',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_aasenterprises',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063203',
    'dbparent' => '',
  ),
  55 =>
  array (
    'name' => 'FTSERVICES',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy55',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_ftservices',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  56 =>
  array (
    'name' => 'EQUATOR',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy56',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_equator',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063206',
    'dbparent' => '',
  ),
  57 =>
  array (
    'name' => 'SARWARINT',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy57',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_sarwarint',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  58 =>
  array (
    'name' => 'ANDROID',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy58',
    'dbpassword' => $dbpass ?? 'Pakistan1947',
    'dbname' => 'pakerp_android',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  59 =>
  array (
    'name' => 'VNLAKHANI',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy59',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_vnlakhani',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063210',
    'dbparent' => '',
  ),
  60 =>
  array (
    'name' => 'ALIAINTL',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy60',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_aliaintl',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063214',
    'dbparent' => '',
  ),
  61 =>
  array (
    'name' => 'ATHARANDCO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy61',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_atharandco',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  62 =>
  array (
    'name' => 'SAE',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy62',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_sae',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  63 =>
  array (
    'name' => 'KIDSCARE',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy63',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_kidscare',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  64 =>
  array (
    'name' => 'COTPAKOLD',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy64',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_cotpakold',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  65 =>
  array (
    'name' => 'REMEL',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy65',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_remel',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  66 =>
  array (
    'name' => 'USMANLOGISTICS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy66',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_usmanlogistics',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063216',
    'dbparent' => '',
  ),
  67 =>
  array (
    'name' => 'LINENSDEPOT',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy67',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_linensdepot',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1028040',
    'dbparent' => '',
  ),
  68 =>
  array (
    'name' => 'WAQASSHABBIR',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy68',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_waqasshabbir',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  69 =>
  array (
    'name' => 'MTDEMO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy69',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_mtdemo',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063217',
    'dbparent' => '',
  ),
  70 =>
  array (
    'name' => 'SAACO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy70',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_saaco',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  71 =>
  array (
    'name' => 'REHMANTRADERS',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'SAACO',
    'dbuser' => $dbuser ?? 'pakerp_coy71',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_rehmantraders',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  72 =>
  array (
    'name' => 'KHILJI',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy72',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_khilji',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  73 =>
  array (
    'name' => 'FAHEEMNCO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy73',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_faheemnco',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044116',
    'dbparent' => '',
  ),
  74 =>
  array (
    'name' => 'EXTECPRO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy74',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_extecpro',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  75 =>
  array (
    'name' => 'IDRISNCO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy75',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_idrisnco',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  76 =>
  array (
    'name' => 'MMCA',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy76',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_mmca',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  77 =>
  array (
    'name' => 'IRCOCA',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy77',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_ircoca',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  78 =>
  array (
    'name' => 'MERAJCARGO',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy78',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_merajcargo',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  79 =>
  array (
    'name' => 'MERAJIMPORT',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy79',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_merajimport',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  80 =>
  array (
    'name' => 'ALHAMIDRICE',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'FAHEEMNCO',
    'dbuser' => $dbuser ?? 'pakerp_coy80',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_alhamidrice',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044117',
    'dbparent' => '',
  ),
  81 =>
  array (
    'name' => 'UNIVERSAL2',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy81',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_universal2',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  82 =>
  array (
    'name' => 'ROYALNEW',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy82',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_royalnew',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  83 =>
  array (
    'name' => 'TEST',
    'host' => 'localhost',
    'port' => '',
    'dbname' => 'pakerp_test',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy83',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'app_id' => 'LOCAL DB',
    'dbparent' => '',
  ),
  84 =>
  array (
    'name' => 'BILALCHAIN',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'FAHEEMNCO',
    'dbuser' => $dbuser ?? 'pakerp_coy84',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_bilalchain',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044118',
    'dbparent' => '',
  ),
  85 =>
  array (
    'name' => 'MDLAW',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy85',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_mdlaw',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  86 =>
  array (
    'name' => 'ANWARNCO',
    'host' => 'localhost',
    'port' => '',
    'parent' => '',
    'mapp' => '1',
    'app_id' => '1056502',
    'dbuser' => $dbuser ?? 'pakerp_coy86',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_anwarnco',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  87 =>
  array (
    'name' => 'MIDTRANSFOODS',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy87',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_midtransfoods',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063220',
    'dbparent' => '',
  ),
  88 =>
  array (
    'name' => 'GUARDIAN',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy88',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_guardian',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063223',
    'dbparent' => '',
  ),
  89 =>
  array (
    'name' => 'BMTECH',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'FAHEEMNCO',
    'dbuser' => $dbuser ?? 'pakerp_coy89',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_bmtech',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044119',
    'dbparent' => '',
  ),
  90 =>
  array (
    'name' => 'MRGROUP',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy90',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_mrgroup',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  91 =>
  array (
    'name' => 'HOUSING',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy91',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_housing',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063225',
    'dbparent' => '',
  ),
  92 =>
  array (
    'name' => 'AMNBROKER',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy92',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_amnbroker',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  93 =>
  array (
    'name' => 'TRAZON',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy93',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_trazon',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044121',
    'dbparent' => '',
  ),
  94 =>
  array (
    'name' => 'TILESELECT',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'FAHEEMNCO',
    'dbuser' => $dbuser ?? 'pakerp_coy94',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_tileselect',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1062177',
    'dbparent' => '',
  ),
  95 =>
  array (
    'name' => 'NDR',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy95',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_ndr',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'parent' => 'VNLAKHANI',
    'app_id' => '1063210',
    'dbparent' => '',
  ),
  96 =>
  array (
    'name' => 'BIOSERVE',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy96',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_bioserve',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  97 =>
  array (
    'name' => '7SIGN2',
    'parent' => '7SIGN',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy97',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_7sign2',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  98 =>
  array (
    'name' => 'COWLAS',
    'parent' => '',
    'dbname' => 'pakerp_cowlas',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy98',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  99 =>
  array (
    'name' => 'IFE',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'COWLAS',
    'dbuser' => $dbuser ?? 'pakerp_coy99',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_ife',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  100 =>
  array (
    'name' => 'AZOM',
    'host' => 'localhost',
    'port' => '',
    'parent' => 'COWLAS',
    'dbuser' => $dbuser ?? 'pakerp_coy100',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'dbname' => 'pakerp_azom',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  101 =>
  array (
    'name' => 'MIANSCO',
    'parent' => '',
    'dbname' => 'pakerp_miansco',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy101',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  102 =>
  array (
    'name' => 'IECNET',
    'parent' => '',
    'dbname' => 'pakerp_iecnet',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy102',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  103 =>
  array (
    'name' => 'ABIDNCO',
    'parent' => '',
    'dbname' => 'pakerp_abidnco',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy103',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063232',
    'dbparent' => '',
  ),
  104 =>
  array (
    'name' => 'COTPAKDEMO',
    'parent' => '',
    'dbname' => 'pakerp_cotpakdemo',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy104',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044124',
    'dbparent' => '',
  ),
  105 =>
  array (
    'name' => 'MUSLIMENT',
    'parent' => '',
    'dbname' => 'pakerp_musliment',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy105',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  106 =>
  array (
    'name' => 'KHANBROTHERS',
    'parent' => '',
    'dbname' => 'pakerp_khanbrothers',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy106',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063233',
    'dbparent' => '',
  ),
  107 =>
  array (
    'name' => 'AVANZARENT',
    'parent' => '',
    'dbname' => 'pakerp_avanzarent',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy107',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  108 =>
  array (
    'name' => 'AVANZARNEW',
    'parent' => '',
    'dbname' => 'pakerp_avanzarnew',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy108',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1044106',
    'dbparent' => '',
  ),
  109 =>
  array (
    'name' => 'BABARGLASS',
    'parent' => '',
    'dbname' => 'pakerp_babarglass',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy109',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063235',
    'dbparent' => '',
  ),
  110 =>
  array (
    'name' => 'AERONVISTA',
    'parent' => '',
    'dbname' => 'pakerp_aeronvista',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy110',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063241',
    'dbparent' => '',
  ),
  111 =>
  array (
    'name' => 'PECHSHOS',
    'parent' => 'ASHIYANATRUST',
    'dbname' => 'pakerp_pechshos',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy111',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'mapp' => '1',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  112 =>
  array (
    'name' => 'VTECH',
    'parent' => '',
    'dbname' => 'pakerp_vtech',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy112',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => 'enter',
    'dbparent' => '',
  ),
  113 =>
  array (
    'name' => 'BASIC',
    'parent' => '',
    'dbname' => 'pakerp_basic',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy113',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063244',
    'dbparent' => '',
  ),
  114 =>
  array (
    'name' => 'ANHEXCHANGE',
    'parent' => '',
    'dbname' => 'pakerp_anhexchange',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy114',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063247',
    'dbparent' => '',
  ),
  115 =>
  array (
    'name' => 'ASHIYANATRUST',
    'parent' => '',
    'dbname' => 'pakerp_ashiyanatrust',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy115',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063253',
    'dbparent' => '',
  ),
  116 =>
  array (
    'name' => 'RHOLAB',
    'parent' => '',
    'dbname' => 'pakerp_rholab',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy116',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063256',
    'dbparent' => '',
  ),
  117 =>
  array (
    'name' => 'NOORCORPORATION',
    'parent' => '',
    'dbname' => 'pakerp_noorcorporation',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy117',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1286344',
    'mapp' => '0',
    'dbparent' => '',
  ),
  118 =>
  array (
    'name' => 'CLEARINGV2',
    'parent' => '',
    'dbname' => 'pakerp_clearingv2',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy118',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063260',
    'dbparent' => '',
  ),
  119 =>
  array (
    'name' => 'NUMBERTAINMENT',
    'parent' => '',
    'dbname' => 'pakerp_numbertainment',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy119',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1063267',
    'dbparent' => '',
  ),
  120 =>
  array (
    'name' => 'FUNCTIONGYM',
    'parent' => '',
    'mapp' => '1',
    'dbname' => 'pakerp_functiongym',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy120',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1132876',
    'dbparent' => '',
  ),
  121 =>
  array (
    'name' => 'NOORTEXTILELHR',
    'parent' => '',
    'mapp' => '1',
    'dbname' => 'pakerp_noortextilelhr',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy121',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'app_id' => '1286356',
    'dbparent' => '',
  ),
  122 =>
  array (
    'name' => 'SOCIALBOND',
    'parent' => '',
    'app_id' => '1099003',
    'mapp' => '1',
    'dbname' => 'pakerp_socialbond',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy122',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  123 =>
  array (
    'name' => 'VNLAKHANIBAC',
    'parent' => 'VNLAKHANI    ',
    'app_id' => '1116055',
    'mapp' => '0',
    'dbname' => 'pakerp_vnlakhanibac',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy123',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  124 =>
  array (
    'name' => 'NOORTEXTILE',
    'parent' => '',
    'app_id' => '1131218',
    'mapp' => '1',
    'dbname' => 'pakerp_noortextile',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy124',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  125 =>
  array (
    'name' => 'POLYOZONE',
    'parent' => '',
    'app_id' => '1131283',
    'mapp' => '1',
    'dbname' => 'pakerp_polyozone',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy125',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  126 =>
  array (
    'name' => 'TASMIATRADERS',
    'parent' => '',
    'app_id' => 1132617,
    'mapp' => '1',
    'dbname' => 'pakerp_tasmiatraders',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy126',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  127 =>
  array (
    'name' => 'SANDYCODE',
    'parent' => '',
    'app_id' => 1186951,
    'mapp' => '1',
    'dbname' => 'pakerp_sandycode',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy127',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  128 =>
  array (
    'name' => 'MTCLEARING',
    'parent' => '',
    'app_id' => 1354546,
    'mapp' => '1',
    'dbname' => 'pakerp_mtclearing',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy128',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  129 =>
  array (
    'name' => '7SIGNNEW',
    'parent' => '7SIGN',
    'app_id' => 1360326,
    'mapp' => '1',
    'dbname' => 'pakerp_7signnew',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy129',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  130 =>
  array (
    'name' => 'AUSAFIND',
    'parent' => '',
    'app_id' => 1362972,
    'mapp' => '0',
    'dbname' => 'pakerp_ausafind',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy130',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  131 =>
  array (
    'name' => 'ALGASO',
    'parent' => '',
    'app_id' => 1362982,
    'mapp' => '0',
    'dbname' => 'pakerp_algaso',
    'host' => 'localhost',
    'port' => '',
    'dbuser' => $dbuser ?? 'pakerp_coy131',
    'dbpassword' => $dbpass ?? 'Petaro9344',
    'collation' => 'utf8_xx',
    'tbpref' => '',
    'dbparent' => '',
  ),
  132 =>
    array (
      'name' => 'CHOTANIBROS',
      'parent' => 'ALGASO',
      'dbparent' => '',
      'app_id' => NULL,
      'mapp' => '0',
      'dbname' => 'pakerp_chotanibros',
      'host' => 'localhost',
      'port' => '',
      'dbuser' => $dbuser ?? 'pakerp_coy132',
      'dbpassword' => $dbpass ?? 'Petaro9344',
      'collation' => 'utf8_xx',
      'tbpref' => '',
    ),
    133 =>
    array (
      'name' => 'EQUATOR2',
      'parent' => 'EQUATOR',
      'dbparent' => '',
      'app_id' => NULL,
      'mapp' => '0',
      'dbname' => 'pakerp_equator2',
      'host' => 'localhost',
      'port' => '',
      'dbuser' => $dbuser ?? 'pakerp_coy133',
      'dbpassword' => $dbpass ?? 'Petaro9344',
      'collation' => 'utf8_xx',
      'tbpref' => '',
    ),
  );
